version: '3.8'

services:
  frontend:
    build: ./client
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - VITE_BACKEND_URL=http://backend:8000

  backend:
    build: ./server
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1