name: Simple Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH using appleboy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_IP }}
          username: user                # <-- replace with your SSH username
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/code-app
            git pull origin main